Main:
	gcc Main.c Lab3IO.c -o  main -lm
Main2:
	gcc Main2.c Lab3IO.c -o main2 -lm -fopenmp
Main3:
	gcc Main3.c Lab3IO.c -o main3 -lm -fopenmp
datagen:
	gcc datagen.c Lab3IO.c -o datagen
clean:
	rm main main2 main3 datagen data_input data_output
